EZ-560: Automated Drupal 9 compatibility fixes
srijanone/ezcontent_api pull request #24
Opened 2020-08-25 05:24 UTC by saurabh-2k17

2020-08-25 06:13 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Controller/PreviewView.php
> +    $node = \Drupal::service('entity_type.manager')->getStorage('node')->load($nid);
Please use dependency Injection.

2020-08-25 06:13 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Utils.php
> +    $node_alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $node_id);
Please use dependency Injection.

2020-08-26 05:41 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Controller/PreviewView.php
> +  public function __construct(EntityTypeManagerInterface $entity_type_manager, RouteMatchInterface $route_match) {
use camel case or variable name `$entityTypeManager`

2020-08-26 05:41 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Controller/PreviewView.php
remove unwanted spaces, format the file.

2020-08-26 05:41 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Controller/PreviewView.php
remove unwanted spaces, format the file.

2020-08-26 05:41 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Utils.php
remove space

2020-08-26 05:41 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Utils.php
> +  public function __construct(EntityTypeManagerInterface $entity_type_manager, ConfigFactoryInterface $config_factory_interface) {
use camel case for variable

2020-08-26 05:41 UTC, arshadkhan53 commented on modules/ezcontent_preview/src/Utils.php
remove space

2020-08-27 04:47 UTC, vaibhavjain-in requested changes
@saurabh-2k17 please cater to feedback.

2020-08-27 04:47 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Controller/PreviewView.php
> +  // Based on the checbox it eturns an iframe output on the.
Why do we have this comment here ? It is outside the scope of a method / variable.

2020-08-27 04:47 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Controller/PreviewView.php
> +   * Homepage or the another tab.
Please improve comments, include params passed into the method.

2020-08-27 04:47 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Controller/PreviewView.php
> +    // return empty array.
This can be one liner comment.

2020-08-27 04:47 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Controller/PreviewView.php
>        '#markup' => '',
Type is not required, it is default.
https://api.drupal.org/api/drupal/developer%21topics%21forms_api_reference.html/7.x#markup

2020-08-27 04:47 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Entity/Preview.php
>    public $token_time;
Please use camelCases.

2020-08-27 04:47 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Entity/Preview.php
>    public $content_entity;
Please use camelCases.

2020-08-27 04:47 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Utils.php
> +    // module to generate token and pass it to Drupal.
Improve comment, this does not make sense.

2020-08-27 07:32 UTC, arshadkhan53 approved these changes
LGTM

2020-08-27 09:31 UTC, vaibhavjain-in approved these changes
LGTM

2020-08-27 10:48 UTC, merged